url=https://opensource-demo.orangehrmlive.com/
browser=chrome
username=Admin
password=admin123

tester=Vishnuvardhan
reportName=Automation Test Report
documentTitle=Test Execution Report
theme=dark

excelPath=./testData/OrangeHRMData.xlsx